idf_component_register(SRCS "main.c"
                            "Communication/Uart/Uart.c"
                            "Communication/RS485/RS485.c"
                            "Communication/Ble_control/Ble_control.c"
                            "Communication/Internet/Mesh/mesh.c"
                            "Communication/Internet/Mesh/mesh_netif.c"
                            "Communication/Internet/dual_net/dual_net.c"
                            "Communication/Can/can_extended.c"
                            "Task/appTask.c"
                            "Tool/app_crc.c"
                            "Tool/app_enc.c"
                            "Tool/Json_data.c"
                            "Tool/app_mem.c"
                            "Tool/SelfRecovery.c"
                            
                            
                            "DataStorage/SPIFFS/spiffs_config.c"
                            "DataStorage/Log/log.c"
                            "DataStorage/SqLite/SqLite.c"
                            "DataStorage/SqLite/sqllib1.c"
                            "Protocol/Can/can_json_parser.c"
                            "Protocol/ModBus/modbus_cmd.c"
                            "Protocol/ModBus/modbus_json_parser.c"
                            "Protocol/SCPI/scpi_dynamic.c"
                            "ConfigData/ConfigData.c"
                            "ConfigData/Externaldevice.c"
                            "ConfigData/aging_config.c"
                            "APP/MQTT/mqtt_app.c"
                            "APP/HTTP/GetProto.c"
                            "APP/OTA/ota.c"

                            INCLUDE_DIRS 
                            "Communication/Uart"
                            "Communication/RS485"
                            "Communication/Ble_control"
                            "Communication/Internet/Mesh"
                            "Communication/Internet/dual_net"
                            "Communication/Can"
                            "Task"
                            "Tool"
                            "DataStorage/SPIFFS"
                            "DataStorage/Log"
                            "DataStorage/SqLite"
                            "Protocol/ModBus"
                            "Protocol/Can"
                            "Protocol/SCPI"
                            "ConfigData"
                            "APP/MQTT"
                            "APP/HTTP"
                            "APP/OTA"                                                                                
                    )
